version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
#  backend:
#    build:
#      context: ./backend
#      dockerfile: Dockerfile
#    container_name: backend
#    working_dir: /app
#    volumes:
#      - ./backend:/app
#    ports:
#      - "8080:8080"
